## Day 1 - Numpy Chapter 1

### What is Numpy?
 - Introduction to Numpy:-
  - Numpy is a Python Package and it stands for Numerical Python.
  - This was created in 2005 and it was developed by Travis Oliphant.
  - It Provides lot of Functions to work in a domain of Linear Algebra and Matrix.
  - It provides function related to to Arrays.
  - It creates an Array called ndarray.
  - Most of thge part of numpy created in C and C++.

### Operations in Numpy 
  - Mathematical and Statistical and Logical Operations on Array.
  - It is used for Scientific Calculation.
  - Operations are related to mathematics, Statistics, Linear Algebra and Random Number Generations.
  - Transformation and routine for shape manipulation of the Array.

In [1]:
%%timeit

a = []

for i in range(1,15):
    a.append(i**2)
    

3.43 µs ± 298 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%timeit [i**2 for i in range(1,15)]

3.08 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Numpy

In [3]:
# importing numpy as np
import numpy as np 

In [4]:
x = [1,2,3]
x

[1, 2, 3]

In [6]:
type(x)

list

In [7]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
type(x)

numpy.ndarray

## 1D Array

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a = [1,2,3,4]
arr = np.array(a)
arr

array([1, 2, 3, 4])

In [13]:
# take user input
a = []
cnt = 1
for i in range(int(input("How many elements you want: "))):
    val = eval(input(f"Enter the value{cnt}: "))
    a.append(val)
    cnt+=1
b = np.array(a)
b

How many elements you want: 6
Enter the value1: 12
Enter the value2: 24
Enter the value3: 59
Enter the value4: 84
Enter the value5: 45
Enter the value6: 51


array([12, 24, 59, 84, 45, 51])

In [18]:
# take user input
a = []
cnt = 1
n=int(input("How many elements you want: "))
for i in range(n):
    val = eval(input(f"Enter the value{cnt}: "))
    a.append(val)
    cnt+=1
b = np.array(a)
b.reshape(n).T

How many elements you want: 6
Enter the value1: 12
Enter the value2: 21
Enter the value3: 42
Enter the value4: 26
Enter the value5: 54
Enter the value6: 85


array([12, 21, 42, 26, 54, 85])

#### 2D Array

In [25]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a.shape

(2, 3)

In [27]:
# checking the type 
type(a)

numpy.ndarray

In [30]:
# To check the Dimensions
print(np.ndim(a))
print(a.ndim)

2
2


In [31]:
# checking the Dtype
a.dtype

dtype('int32')

In [32]:
print(a.dtype)

int32


## 3D Array (matrices, rows, columns)

In [33]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 5, 9]]])

In [36]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,5,2]],[[7,5,3],[9,5,1]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [8, 5, 2]],

       [[7, 5, 3],
        [9, 5, 1]]])

In [37]:
a.ndim

3

In [38]:
np.ndim(a)

3

In [39]:
a.shape

(3, 2, 3)

In [40]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,5,2]],[[7,5,3],[9,5,1]],[[1,2,6],[8,7,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [8, 5, 2]],

       [[7, 5, 3],
        [9, 5, 1]],

       [[1, 2, 6],
        [8, 7, 9]]])

In [41]:
b.shape

(4, 2, 3)

In [43]:
b.ndim

3

In [45]:
c = b.T
c

array([[[1, 7, 7, 1],
        [4, 8, 9, 8]],

       [[2, 8, 5, 2],
        [5, 5, 5, 7]],

       [[3, 9, 3, 6],
        [6, 2, 1, 9]]])

In [46]:
c.shape

(3, 2, 4)

## Attribute of Numpy 

In [47]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# gives shape of an matrix or array in the row and columnwise.
a.shape
# it says 2 rows and 3 columns 

(2, 3)

In [49]:
# Return the total no. of observation in an array.
a.size

6

In [50]:
# this will change the shape of an array Temporary
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
np.reshape(a)

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [59]:
# Transpose
# this will convert rpws into column amd columns into rows 
a.T
# changes the shape of an array/ matrix


array([[1, 3, 5],
       [2, 4, 6]])

In [60]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
# It will return you the dimensions of an Array.
a.ndim

2

### Joining of Array 

In [62]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [63]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.arange(1,7).reshape(3,2).T

array([[1, 3, 5],
       [2, 4, 6]])

In [67]:
np.arange(1,7).reshape(2,3).shape

(2, 3)

In [68]:
np.arange(1,7).reshape(2,3).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
np.arange(1,7).reshape(2,3).T.shape

(3, 2)

In [70]:
a = np.arange(1,7).reshape(2,3)

b = np.arange(7,13).reshape(2,3)

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

### Concatenate

In [73]:
#a.Concatenate((arr1,arr2))
# It is used to join two different Array and it takes tuples.


In [74]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
np.concatenate((a,b),axis =1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [78]:
np.concatenate((a,b),axis =1,dtype= 'float')

array([[ 1.,  2.,  3.,  7.,  8.,  9.],
       [ 4.,  5.,  6., 10., 11., 12.]])

In [77]:
np.concatenate((a,b),axis =1,dtype = 'object')

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 10, 11, 12]], dtype=object)

In [79]:
np.concatenate((b,a), axis= 1)

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [80]:
np.concatenate((b,a))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

### hstack and vstack

In [81]:
# hstack 
# it is used to concatenate two differents Arrays horizontally 
# (column wise)
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [83]:
np.hstack((b,a))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [82]:
# vstack
# It is used to concatenate two different Array vertically 
# (row wise)
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.vstack((b,a))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [85]:
# stack
# it is usewd to convert 2D Array into 3D Array

np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
np.stack((b,a))

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [87]:
# ravel 
# It is used to convert 2D into 1D Array
# Return a contiguous flattened array.
# np.ravel(a)
print(a)
np.ravel(a)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

## Append

In [88]:
# append(arr,list of element)
# It is used to add the element in the existing Array.

c = np.arange(1,7)
c

array([1, 2, 3, 4, 5, 6])

In [89]:
np.append(c,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.append(a,[[7,8,9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.append(a,[[7,8,9]],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [95]:
np.append(a,[[7],[8],[9]],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

### Insert

In [97]:
# insert 
# it is used to add the element at specific index.

In [98]:
d = np.arange(2,6)
d

array([2, 3, 4, 5])

In [99]:
np.insert(d,0,56)

array([56,  2,  3,  4,  5])

In [100]:
d

array([2, 3, 4, 5])

In [101]:
np.insert(d,-1,65)

array([ 2,  3,  4, 65,  5])

In [102]:
np.insert(d,-2,65)

array([ 2,  3, 65,  4,  5])

In [103]:
np.insert(d,-0,65)

array([65,  2,  3,  4,  5])

## Delete 

In [104]:
# delete(array, list of element index)
# It is used to delete element the from the array.
a = np.arange(1,6)

In [105]:
a

array([1, 2, 3, 4, 5])

In [106]:
np.delete(a,[0,1])

array([3, 4, 5])

In [107]:
np.delete(a,[0])

array([2, 3, 4, 5])

In [108]:
np.delete(a,[-1])

array([1, 2, 3, 4])

In [109]:
np.delete(a,[-2,-2])

array([1, 2, 3, 5])

In [110]:
np.delete(a,[-9])

IndexError: index -9 is out of bounds for axis 0 with size 5

In [120]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
np.delete(b,1,0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [124]:
np.delete(b, np.s_[::2], 1)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [122]:
np.delete(b,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
np.delete(a,,axis=0)

SyntaxError: invalid syntax (364119787.py, line 1)

In [111]:
np.delete(a,[:])

SyntaxError: invalid syntax (1865885327.py, line 1)

In [112]:
np.delete(a,[,:])

SyntaxError: invalid syntax (1821770178.py, line 1)

In [125]:
a

array([1, 2, 3, 4, 5])

In [126]:
np.delete(a,0)

array([2, 3, 4, 5])

### Day 2 - Numpy Array Creation Routine. Chapter 2

In [127]:
import numpy as np

In [130]:
# empty(shape,dtype)
# It creates an uninitialize Array of Specified Shape and Datatype
np.empty([3,2])

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313],
       [2.12199579e-313, 2.54639495e-313]])

In [132]:
np.empty([3,2])

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313],
       [2.12199579e-313, 2.54639495e-313]])

In [134]:
a = np.empty([2,2])
a

array([[2.12199579e-314, 4.67296746e-307],
       [6.85763116e-321, 3.79442416e-321]])

In [135]:
a.dtype

dtype('float64')

In [136]:
np.empty([3,2])

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313],
       [2.12199579e-313, 2.54639495e-313]])

In [137]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.03358533e-320],
       [1.97345609e-312, 1.37959740e-306, 2.29178686e-312]])

In [138]:
np.empty([2,3])

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313]])

In [139]:
np.empty([2, 2])        #uninitialized

array([[1.03358533e-320, 1.97345609e-312],
       [1.37959740e-306, 2.29178686e-312]])

In [140]:
np.empty([3,2],dtype='str')

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [141]:
np.empty([3,2],dtype='str').T

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [142]:
np.empty([3,2],dtype='str').shape

(3, 2)

In [143]:
# Zeros(shape, dtype)
# it Returns new array of Specialized size and type filled with ones
np.zeros([3,2])
# bydefault dtype is float

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [144]:
np.zeros([2,2],dtype='str')

array([['', ''],
       ['', '']], dtype='<U1')

In [145]:
np.zeros([2,3],dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [147]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [148]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [150]:
np.zeros([5,3],dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [151]:
np.zeros([5,3],dtype = float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
np.zeros([5,3],dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [153]:
# ones
# it returns new array of specified size and type filled with ones 
# np.ones([shape],dtype=)
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.ones([5,4],dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [159]:
np.ones(5,dtype='float')

array([1., 1., 1., 1., 1.])

In [157]:
np.ones(5,dtype='object')

array([1, 1, 1, 1, 1], dtype=object)

In [158]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [160]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [161]:
np.ones([5,5],dtype='str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [162]:
# eye()
# it is identity matrix 
# it takes square matrix ---> np.eye(3) means 3x3 matrix
# Initialize "ones" on all diagonal position.
# initialize "zeros" on non-diagonal position.
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [163]:
np.eye(1)

array([[1.]])

In [164]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [165]:
np.eye(3,dtype='float')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [166]:
np.eye(4,dtype='float')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [167]:
np.eye(4,dtype='float')*5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [168]:
np.eye(4,dtype='float')/2

array([[0.5, 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. ],
       [0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0.5]])

In [169]:
np.eye(5,dtype='float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
np.eye(4,dtype='float')+3

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [174]:
np.eye(4,dtype='float')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [175]:
np.eye(5,dtype='float')+1

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [177]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [179]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [180]:
np.eye(5,5)+3

array([[4., 3., 3., 3., 3.],
       [3., 4., 3., 3., 3.],
       [3., 3., 4., 3., 3.],
       [3., 3., 3., 4., 3.],
       [3., 3., 3., 3., 4.]])

In [181]:
np.eye(4,dtype=float)+2

array([[3., 2., 2., 2.],
       [2., 3., 2., 2.],
       [2., 2., 3., 2.],
       [2., 2., 2., 3.]])

In [182]:
# full()
# this function will initailize the elemet in the given values 
# np.full(shape,values)
a = np.full([2,2],100)
a

array([[100, 100],
       [100, 100]])

In [185]:
a.dtype

dtype('int32')

In [186]:
np.full(12,100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [184]:
np.full(12,100).reshape(6,2)

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

In [187]:
np.full([3,4],100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [188]:
b=np.full([4,5],12,dtype='float')
b

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

In [189]:
b.dtype

dtype('float64')

In [190]:
c= np.full([3,3],12.)
c

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]])

In [191]:
print(c.dtype)

float64


In [192]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [195]:
a = np.diag(np.arange(5))

In [196]:
# it will return the diagnoanl value which in an array exists
np.diag(a)

array([0, 1, 2, 3, 4])

In [197]:
np.diag([1,2,3,4]).reshape(16,)

array([1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4])

In [198]:
np.diag([1,2,3,4]).reshape(1,16)

array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4]])

In [199]:
np.diag([1,2,3,4]).reshape(1,16)

array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4]])

In [201]:
np.diag(np.arange(1,16))

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [204]:
np.diag(np.arange(1,16)).reshape(225,)

array([ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 15])

In [205]:
np.diag(np.arange(1,16)).reshape(1,225)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 

In [215]:
# randint()
# tihis functionns is used to generate a random number between a goven range
# np.random.randint(min,max,total values)
np.random.randint(1,10,10)

array([9, 5, 7, 8, 8, 3, 3, 7, 1, 1])

In [227]:
np.random.seed(111)
np.random.randint(1,10,9)

array([5, 5, 5, 7, 4, 3, 7, 3, 9])

In [243]:
np.random.seed(111)
np.random.randint(1,10,10)

array([5, 5, 5, 7, 4, 3, 7, 3, 9, 8])

In [244]:
np.random.randint(-20,10,10)

array([  5, -13,  -8, -10, -19,  -4,   4,   8,  -6, -18])

In [245]:
np.random.randint(20,10,10)

ValueError: low >= high

In [246]:
# rand()
# this function is used to generate a random value,
# between 0 to 1
np.random.rand(2,3)

array([[0.23772645, 0.08119266, 0.66960024],
       [0.62124292, 0.27425353, 0.46622141]])

In [247]:
np.random.rand(2,3).T

array([[0.11836775, 0.79396256],
       [0.07395756, 0.84056965],
       [0.90077418, 0.81520746]])

In [249]:
a  = np.random.rand(4,4)
a

array([[0.7278491 , 0.32281393, 0.40054555, 0.3189664 ],
       [0.94722183, 0.91870836, 0.81384438, 0.03407709],
       [0.94337287, 0.95043916, 0.80659105, 0.48127804],
       [0.96675923, 0.41697908, 0.31884013, 0.01644282]])

In [250]:
type(a)

numpy.ndarray

In [251]:
a.dtype

dtype('float64')

In [252]:
a.ndim

2

In [253]:
# randn
# it will genrate a random value closed to 'zero'
# it will return a positive or negative value close to 'zero'
np.random.randn(5)

array([ 0.24350846, -1.51720425, -0.43893216, -0.43991633,  0.44882178])

In [254]:
np.random.randn(2,3)

array([[-0.85928929,  1.5594253 , -0.18016486],
       [-0.66653779,  1.91584296, -0.93996453]])

In [272]:
np.random.seed(111)
np.random.randn(2,4)

array([[-1.13383833,  0.38431919,  1.49655378, -0.3553823 ],
       [-0.78753354, -0.45943891, -0.05916877, -0.3541735 ]])

In [274]:
np.random.randn(4,4)

array([[-0.4080822 , -0.06794759, -0.95242666, -0.1106774 ],
       [ 0.57059429,  0.91542017, -1.66934051,  0.48271364],
       [-0.31047267,  2.39468973,  1.55093092, -0.64646518],
       [-0.92893724, -1.65497614,  0.3501925 , -0.14175652]])

In [273]:
np.random.randn(12,)

array([-0.73552305, -1.18393989,  0.23889413, -0.58992026, -1.44058512,
        0.77370311, -1.02796733, -0.09098625,  0.492003  ,  0.4246722 ,
        1.28304882,  0.31598645])

In [275]:
np.random.randn(1,12)

array([[ 0.52108179, -0.02090086, -1.74384395, -0.79915888, -1.30357043,
         0.178105  , -0.33440236, -0.30602713, -0.33240557,  1.96294734,
         0.71924249,  1.14288651]])

    ## seed() functions
    we know that randint() generates random number a new set of number everytime we run the program a new set of random numbers is generated but what if we want to fix this generation of number in this case we use 'seed' function

In [276]:
np.random.seed(0)
np.random.randint(1,100,10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [277]:
np.random.seed(0)
np.random.randint(1,100,11)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71])

In [288]:
a = np.random.seed(0)
a
np.random.randint(1,100,11)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71])

In [289]:
a = np.random.seed(0)
# a
np.random.randint(1,100,11)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71])

In [290]:
np.random.seed(1)
np.random.randint(1,3,10)

array([2, 2, 1, 1, 2, 2, 2, 2, 2, 1])

In [291]:
np.random.seed(0)
np.random.randint(1,100,11)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71])

## Reshape of an Array

In [301]:
a = np.random.randint(1,100,12)

In [302]:
a

array([24, 36, 76, 56, 29, 35,  1,  1, 37, 54,  6, 39])

In [303]:
a.reshape(4,3)

array([[24, 36, 76],
       [56, 29, 35],
       [ 1,  1, 37],
       [54,  6, 39]])

In [304]:
a.reshape(3,4)

array([[24, 36, 76, 56],
       [29, 35,  1,  1],
       [37, 54,  6, 39]])

In [305]:
a.reshape(12,)

array([24, 36, 76, 56, 29, 35,  1,  1, 37, 54,  6, 39])

In [306]:
a.reshape(1,12)

array([[24, 36, 76, 56, 29, 35,  1,  1, 37, 54,  6, 39]])

## Functions in Numpy 

In [314]:
# arange()
# it is an array of evenly spaced numbers just like a python's list
# array with numerical python 
# np.arange(start,stop, step, dtype)
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [316]:
np.arange(1,20,2,dtype='float')

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [317]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [318]:
np.arange(20,10,-1).reshape(2,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [319]:
np.arange(20,10,-1).reshape(2,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [320]:
np.arange(20,10,-1).reshape(2,5).T

array([[20, 15],
       [19, 14],
       [18, 13],
       [17, 12],
       [16, 11]])

In [321]:
# linspace()
# np.linspace(start,stop,num,endpoint,retstep)
a=np.linspace(10,20)
a
# bydefault it will print 50 no. of obseravtions 

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [322]:
a.size

50

In [323]:
np.linspace(10,20,num=20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [324]:
np.linspace(10,20,num=20).size

20

In [325]:
np.linspace(10,20,num=20,endpoint=False)
# endpoint will not consider the last element which was 20 in this case

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [326]:
np.linspace(10,20,num=20,endpoint=False,retstep=True)
# restep will let you know what is the increment size betn the obseravtions

(array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
        15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5]),
 0.5)

In [327]:
10/20

0.5

In [328]:
np.linspace(10,20,num=10,endpoint=False,retstep=True)
# restep will let you know what is the increment size betn the obseravtions

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), 1.0)

In [329]:
10/10

1.0

In [330]:
# logspace 
# logspace doesn't have retstep
np.logspace(10,20,num=20)
# it will give us logarithm values 
# base bydefault is 10
# # bydefault it will print 50 no. of obseravtions 

array([1.00000000e+10, 3.35981829e+10, 1.12883789e+11, 3.79269019e+11,
       1.27427499e+12, 4.28133240e+12, 1.43844989e+13, 4.83293024e+13,
       1.62377674e+14, 5.45559478e+14, 1.83298071e+15, 6.15848211e+15,
       2.06913808e+16, 6.95192796e+16, 2.33572147e+17, 7.84759970e+17,
       2.63665090e+18, 8.85866790e+18, 2.97635144e+19, 1.00000000e+20])

In [331]:
# lets change the base 
np.logspace(10,20,num=20,base=3)

array([5.90490000e+04, 1.05275908e+05, 1.87691864e+05, 3.34627706e+05,
       5.96593265e+05, 1.06364033e+06, 1.89631834e+06, 3.38086396e+06,
       6.02759614e+06, 1.07463405e+07, 1.91591857e+07, 3.41580835e+07,
       6.08989697e+07, 1.08574139e+08, 1.93572137e+08, 3.45111392e+08,
       6.15284174e+08, 1.09696354e+09, 1.95572886e+09, 3.48678440e+09])

In [332]:
# lets try to save an array 
a=np.arange(1,7).reshape(2,3)

In [333]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [334]:
# lets save this array 
np.savetxt('arrray.txt',a)

In [335]:

# let read the array file which we saved in a txt format 
y = np.loadtxt('arrray.txt')
y
# the dtype is 'float' 


array([[1., 2., 3.],
       [4., 5., 6.]])

In [336]:

# lets change the dtype
y = np.loadtxt('arrray.txt',dtype='int')
y

C:\Users\HRISHIKESH\AppData\Local\Temp\ipykernel_13204\1743094509.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  y = np.loadtxt('arrray.txt',dtype='int')


array([[1, 2, 3],
       [4, 5, 6]])