## Series

In [3]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings("ignore")

In [4]:
# syntax for series :- (data,index,dtype)

In [6]:
# creating a empty series

a = pd.Series()
a

Series([], dtype: float64)

In [7]:
print(a)

Series([], dtype: float64)


In [8]:
# creating a series with python list

b = pd.Series(data=["one","two","three","four"])
b
# if you notice something bydefaultthe index values starts from "0".

0      one
1      two
2    three
3     four
dtype: object

In [9]:
# lets change the index start from "1"
c = pd.Series(data= ["one","two","three","four"], index=[1,2,3,4] )
c

1      one
2      two
3    three
4     four
dtype: object

In [10]:
# alternate way to do with python list is to save it in a variable.
list1 = ["one","two","three","four"]
d = pd.Series(data=list1,index=[1,2,3,4])
d

1      one
2      two
3    three
4     four
dtype: object

In [11]:
list2 = ['five','four','three']
e = pd.Series(data=list2,index=[5,4,3])
e

5     five
4     four
3    three
dtype: object

In [13]:
# creating a series with python dict

dic = {1:'one',2:"two",3:'three'}
a = pd.Series(data=dic)
a

1      one
2      two
3    three
dtype: object

In [14]:
dic = {1:'one',2:"two",3:'three'}
a = pd.Series(data=dic,index=[1,2,'C'])
a

1    one
2    two
C    NaN
dtype: object

In [15]:
# creating series with numpy array

i = np.array([1,2,3])
d = np.array(['one','two','three'])

s = pd.Series(data=d,index=i)
s

1      one
2      two
3    three
dtype: object

In [16]:
i = np.array([1,2,3])
d = np.array(['one','two','three'])


# changeing the parameters 
s = pd.Series(index=i,data=d)
s

1      one
2      two
3    three
dtype: object

In [17]:
i = np.array([1,2,3])
d = np.array(['one','two','three'])


# changeing the parameters 
s = pd.Series(d,i)
s

1      one
2      two
3    three
dtype: object

In [18]:
i = np.array([1,2,3])
d = np.array(['one','two','three'])


# changeing the parameters 
s = pd.Series(i,d)
s

one      1
two      2
three    3
dtype: int32

In [19]:
# creating a series with scalar value

s = pd.Series(5,index=[1,2,3,4,5])
s

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [20]:
# creating a series with scalar value

s = pd.Series(5,index=[1,2,3,4,5])
print(s)

1    5
2    5
3    5
4    5
5    5
dtype: int64


In [21]:
# creating a series with scalar value

s = pd.Series(5,index=np.arange(5))
s

0    5
1    5
2    5
3    5
4    5
dtype: int64

## DataFrame 

In [22]:
# Creating Empty df 

df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [23]:
# Creating Empty df 

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [24]:
# creating df with python list 
data = ['one','two','three','four','five']

df = pd.DataFrame(data)
df

0
0    one
1    two
2  three
3   four
4   five

In [28]:
col = ["Name","Age","ML","Python"]

dat = [
        ["Rishi",20,76,80],
        ["Aditya",22,89,78],
        ["Sahil",21,78,89],
        ["Nishant",23,78,67],
        ["Sanjil",22,88,87]
    
]

df = pd.DataFrame(data = dat,columns=col)
df

Name  Age  ML  Python
0    Rishi   20  76      80
1   Aditya   22  89      78
2    Sahil   21  78      89
3  Nishant   23  78      67
4   Sanjil   22  88      87

In [29]:
col = ["Name","Age","ML","Python"]

dat = [
        ["Rishi",20,76,80],
        ["Aditya",22,89,78],
        ["Sahil",21,78,89],
        ["Nishant",23,78,67],
        ["Sanjil",22,88,87]
    
]

df = pd.DataFrame(data = dat,columns=col,
                  index = ['Rank1','Rank2',
                          'Rank3','Rank4',
                          'Rank5'])
df

Name  Age  ML  Python
Rank1    Rishi   20  76      80
Rank2   Aditya   22  89      78
Rank3    Sahil   21  78      89
Rank4  Nishant   23  78      67
Rank5   Sanjil   22  88      87

In [30]:
#Creating Df with Python Dictionary

name = ["javed","ramachal","rajat","swapnil","rohit","prabhat","shweta","Sid","yuvi","siddu"]
age = [22,23,24,25,23,21,19,23,24,25]
ml = [67,78,67,78,89,90,87,67,45,89]
python =[89,78,65,67,78,67,56,57,89,78]

dic = {
    'Name':name,
    'Age':age,
    'ML':ml,
    'Python':python
}


df = pd.DataFrame(data=dic)
df

Name  Age  ML  Python
0     javed   22  67      89
1  ramachal   23  78      78
2     rajat   24  67      65
3   swapnil   25  78      67
4     rohit   23  89      78
5   prabhat   21  90      67
6    shweta   19  87      56
7       Sid   23  67      57
8      yuvi   24  45      89
9     siddu   25  89      78

In [31]:
#Creating Df with Python Dictionary

name = ["javed","ramachal","rajat","swapnil","rohit","prabhat","shweta","Sid","yuvi","siddu"]
age = [22,23,24,25,23,21,19,23,24,25]
ml = [67,78,67,78,89,90,87,67,45,89]
python =[89,78,65,67,78,67,56,57,89,78]

dic = {
    'Name':name,
    'Age':age,
    'ML':ml,
    'Python':python
}


df = pd.DataFrame(data=dic,index=np.arange(1,11))
df

Name  Age  ML  Python
1      javed   22  67      89
2   ramachal   23  78      78
3      rajat   24  67      65
4    swapnil   25  78      67
5      rohit   23  89      78
6    prabhat   21  90      67
7     shweta   19  87      56
8        Sid   23  67      57
9       yuvi   24  45      89
10     siddu   25  89      78

In [32]:
#Creating Df with Numpy ArraY

arr = np.arange(1,5).reshape(2,2)
df = pd.DataFrame(arr)
df

# bydefault it has taken 0,1 as index and column name also

0  1
0  1  2
1  3  4

In [33]:
# lets assign column name to the above program

arr = np.arange(1,5).reshape(2,2)
df = pd.DataFrame(arr,columns=['A','B'])
df


A  B
0  1  2
1  3  4

In [34]:
arr

array([[1, 2],
       [3, 4]])

In [35]:
# creating df with Series

d = {
    'one':pd.Series([1,2,3], index=['a','b','c']),
    'two':pd.Series([1,2,3,4], index=['a','b','c','d'])
}

df = pd.DataFrame(d)
df


one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

  - whenever there is "Nan" value in any column then the datatype of that column will get convert from 'int' to 'float'

In [36]:
d = {
    "one":pd.Series([1,2,3],index=["a","b","c"]),
    "two":pd.Series([1,2,3,4],index=["A","b","c","d"])
}

df = pd.DataFrame(d)
df

one  two
A  NaN  1.0
a  1.0  NaN
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [38]:
d = {
    "one":pd.Series([1,2,3],index=["a","b","c"]),
    "two":pd.Series([1,2,3,4],index=["A","b","c","d"])
}

df = pd.DataFrame(d)
df

one  two
A  NaN  1.0
a  1.0  NaN
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [39]:
#Creating df With Random

df = pd.DataFrame(np.random.randn(10,4),columns=['A','B','C','D'])
df

A         B         C         D
0  1.431574  1.049149 -1.020916 -1.029468
1  0.751867  2.412749 -0.829589 -2.469423
2 -0.569617 -0.330058 -0.695967 -0.585312
3 -0.796977 -1.588974  1.038708  2.013703
4 -0.038771 -0.229320 -1.268779 -0.076739
5 -0.103679 -1.648026 -0.959997  0.036886
6  0.412267  0.093083  0.027617  0.417310
7  0.359427 -1.109175  0.208357 -2.270436
8  1.054539  0.452451 -0.915560 -1.211913
9 -1.428759  0.892998 -0.881587  0.358321

## Panel

In [40]:
data = np.random.rand(2,4,5)
data
# 2 matrices
# 4 rows in each matrices
# 5 columns or 5 values in each rows

array([[[0.1874747 , 0.58496129, 0.33568218, 0.22806615, 0.68372835],
        [0.8705839 , 0.74915433, 0.34412084, 0.03253669, 0.15814897],
        [0.13870508, 0.44932325, 0.84781119, 0.78082202, 0.56990124],
        [0.09035142, 0.25720906, 0.85257789, 0.5798764 , 0.36471153]],

       [[0.20387248, 0.36188869, 0.04945102, 0.32207868, 0.6077857 ],
        [0.44762065, 0.02041346, 0.45226055, 0.86293463, 0.68976145],
        [0.89777992, 0.66693742, 0.47113068, 0.60058654, 0.53910695],
        [0.71366366, 0.00925934, 0.66936529, 0.4852991 , 0.31065492]]])

In [41]:
np.random.randn(2,4)

array([[-1.99390811, -0.59136312,  0.75095987, -0.89054317],
       [ 1.30648911,  1.1050203 , -0.76216748, -1.16263553]])

In [42]:
data = np.random.rand(2,4,5)
p = pd.Panel(data)
p

AttributeError: module 'pandas' has no attribute 'Panel'

In [43]:
data = np.random.rand(2,4,5)
p = pd.panel(data)
p

AttributeError: module 'pandas' has no attribute 'panel'