### Slicing in Numpy - Chapter 3

In [1]:
import numpy as np 

## 1D

In [2]:
a = np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [3]:
a[::]

array([10, 20, 30, 40, 50, 60])

In [4]:
a[0:6:1]

array([10, 20, 30, 40, 50, 60])

In [5]:
a[0:]

array([10, 20, 30, 40, 50, 60])

In [6]:
a[::-1]

array([60, 50, 40, 30, 20, 10])

In [7]:
a[0:6:2]

array([10, 30, 50])

In [8]:
a[:4]

array([10, 20, 30, 40])

In [9]:
a[2:]

array([30, 40, 50, 60])

In [10]:
a[::2]

array([10, 30, 50])

In [11]:
a[-1::1]

array([60])

In [12]:
a[-1::-1]

array([60, 50, 40, 30, 20, 10])

In [13]:
a[::-1]

array([60, 50, 40, 30, 20, 10])

### 2D

In [14]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
b[1,1]

50

In [17]:
# if you see the abouve output it just giving the output 
# but not in the form of an array 
# if i try the same abpve output in array form
b[1:2,1:2]
# here i did the slicing and due to that we got the output in, 
# array form


array([[50]])

In [18]:
b[:,1:]

array([[20, 30],
       [50, 60]])

In [19]:
b[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [20]:
b= np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [21]:
b[2,1]

80

In [24]:
b[2,1:2]
# 1d

array([80])

In [25]:
b[2:3,1:2]
# 2d

array([[80]])

In [26]:
b[0,1:2]

array([20])

### Arithmatic Operator

In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.shape(a)

(3, 3)

In [31]:
a.shape

(3, 3)

In [32]:
b.shape

(3, 3)

In [33]:
# addition
np.add(a,b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
np.add(b,a)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
c = np.array([10,20,30])
c

array([10, 20, 30])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.add(a,c)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [39]:
np.add(c,a)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [40]:
np.subtract(a,c)

array([[ -9, -18, -27],
       [ -6, -15, -24],
       [ -3, -12, -21]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
c

array([10, 20, 30])

In [41]:
np.subtract(c,a)

array([[ 9, 18, 27],
       [ 6, 15, 24],
       [ 3, 12, 21]])

In [44]:
np.divide(a,b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [45]:
np.mod(a,c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### View  And Copy - Chapter 4
  - when we slice a subarray from an array it may be done by two Array 
   - 1. it is making view
   - 2. Using a copy of it
  - But there is some difference between both of them.
  - if you make a view of an array any changes made to the array will be replicated to Original Array,
  - whereas if you make a copy of it, and make any changes to copied subarray will bot reflect on the Original Array.
  
  - Bydefault an Array is set on View.
  
## View 

In [46]:
import numpy as np 

In [47]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
slicing = a[3:6]

In [49]:
slicing

array([40, 50, 60])

In [50]:
# lets try to change the value of variable 'slicing'
slicing[:]=0
slicing

array([0, 0, 0])

In [52]:
# let try to print the Original Array 
# to see that if it has effected our original array or not
a
# and it has did the changes oin the Original Array

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

### Copy 

In [53]:
b = np.array([10,20,30,40,50,60,70,80,90])
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
slicing=b[3:6].copy()
slicing

array([40, 50, 60])

In [57]:
slicing[:]=0
slicing

array([0, 0, 0])

In [59]:
b
# see, it didn't make any changes to the Original Array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### Numpy Array Selection
#### This is called process Masking.

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
mask = a>4
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
a[mask]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [66]:
name = np.array(["rishi","rohit","aditya","sanjil","nishant"])
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant'], dtype='<U7')

In [67]:
x='rishi'
name==x

array([ True, False, False, False, False])

In [68]:
name[name==x]

array(['rishi'], dtype='<U7')

In [69]:
name[name!=x]

array(['rohit', 'aditya', 'sanjil', 'nishant'], dtype='<U7')

In [70]:
name = np.array(["rishi","rohit","aditya","sanjil","nishant","rishi","rishi","sanjil"])
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant', 'rishi', 'rishi',
       'sanjil'], dtype='<U7')

In [71]:
(name=="rishi") | (name=="sanjil")

array([ True, False, False,  True, False,  True,  True,  True])

In [72]:
name[(name=="rishi") | (name=="sanjil")]

array(['rishi', 'sanjil', 'rishi', 'rishi', 'sanjil'], dtype='<U7')

In [74]:
# select all the values which is not rishi and 
# assign those value as 'Javed'
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant', 'rishi', 'rishi',
       'sanjil'], dtype='<U7')

In [75]:
name[name!='rishi']='Javed'

In [76]:
name

array(['rishi', 'Javed', 'Javed', 'Javed', 'Javed', 'rishi', 'rishi',
       'Javed'], dtype='<U7')

In [78]:
a = np.array([27,4,1,5,7,39])
a

array([27,  4,  1,  5,  7, 39])

In [79]:
np.min(a)

1

In [80]:
np.max(a)

39

In [81]:
np.argmin(a)

2

In [82]:
np.argmax(a)

5

In [83]:
np.sqrt(a)

array([5.19615242, 2.        , 1.        , 2.23606798, 2.64575131,
       6.244998  ])

In [84]:
np.sin(a)

array([ 0.95637593, -0.7568025 ,  0.84147098, -0.95892427,  0.6569866 ,
        0.96379539])

In [85]:
np.cos(a)

array([-0.29213881, -0.65364362,  0.54030231,  0.28366219,  0.75390225,
        0.26664293])

In [86]:
np.quantile(a,0.25)
# Quantile 1 - 25%

4.25

In [87]:
np.quantile(a,0.75)
# Quantile 3 - 75%

22.0

In [88]:
np.quantile(a,0.50)
# Quantile 2 - 50% Median 

6.0