## Series

In [1]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

In [2]:
# syntax for  series:- (data,index,dtype)

In [3]:
# creating a empty series 
a = pd.Series()
a

Series([], dtype: float64)

In [4]:
print(a)

Series([], dtype: float64)


In [5]:
# creating a series with Python list 
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
# creating a series with Python list 
a = pd.Series(data=['one','two','three','four'])
a
# if you notice something bydefaultthe index values starts from "0".  

0      one
1      two
2    three
3     four
dtype: object

In [7]:
# lets change the index start from "1"
c = pd.Series(data=['one','two','three','four'],index=[1,2,3,4])
c

1      one
2      two
3    three
4     four
dtype: object

In [9]:
# alternate way to do with python list is to save it in a variable
a = ['one','two','three','four']
b = pd.Series(data=a,index=[1,2,3,4])
b

1      one
2      two
3    three
4     four
dtype: object

In [10]:
list2 = ['five','four','three']
e = pd.Series(data = list2,index=[5,4,3])
e

5     five
4     four
3    three
dtype: object

In [11]:
# creating a series with python dict
dic = {1:'one',4:'two',3:'three'}
a = pd.Series(data=dic)
a
# As you know the dictionary is in key-value pair,
# here "key" become 'index'
# here "value" become "values"

1      one
4      two
3    three
dtype: object

In [12]:
dic ={
    1:'one',
    2:'two',
    3:'three'
}
a = pd.Series(data=dic, index=[1,2,'C'])
a

1    one
2    two
C    NaN
dtype: object

In [13]:
# creating series with numpy array
i = np.array([1,2,3])
d = np.array(['one','two','three'])
a = pd.Series(data=d,index=i)
a

1      one
2      two
3    three
dtype: object

In [14]:
a = pd.Series(index=i,data=d)
a

1      one
2      two
3    three
dtype: object

In [15]:
a = pd.Series(d,i)
a

1      one
2      two
3    three
dtype: object

In [17]:
a = pd.Series(i,d)
a

one      1
two      2
three    3
dtype: int32

In [18]:
# creating a series with Scalar value

a = pd.Series(5)
a

0    5
dtype: int64

In [19]:
a = pd.Series(5,index=[1,2,3,4,6,8])
a

1    5
2    5
3    5
4    5
6    5
8    5
dtype: int64

In [20]:
# creating a series with scalar value
a = pd.Series(5,index=np.arange(5))
a

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [21]:
a = pd.Series(data = [12,25,45,87,69],index=np.arange(5))
a

0    12
1    25
2    45
3    87
4    69
dtype: int64

## DataFrame

In [25]:
# Creating Empty DataFrame
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [27]:
df.shape

(0, 0)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [29]:
# creating df with Python List
data = ['one','two','three','four','five']
df = pd.DataFrame(data)
df

0
0    one
1    two
2  three
3   four
4   five

In [34]:
data = ['one','two','three','four','five']
df = pd.DataFrame(data,index=[1,2,3,4,5])
df

0
1    one
2    two
3  three
4   four
5   five

In [35]:
# let change the column name
data = ['one','two','three','four','five']
df = pd.DataFrame(data,index=[1,2,3,4,5],columns=['col1'])
df

col1
1    one
2    two
3  three
4   four
5   five

In [38]:
# Creating a Dataset

col = ['Item','Material','Colour','Price']

data = [
    ['Sofa','Wooden','Maroon',25000],
    ['Dining Table','Plywood','Yellow',20000],
    ['Chair','Plastic','Red',1500],
    ['Sofa','Stainless steel','Silver',55000],
    ['Chair','Wooden','Light Blue',2500],
    ['Dining Table','Aluminum','Golden',65000]
]
df = pd.DataFrame(data,columns=col)
df

Item         Material      Colour  Price
0          Sofa           Wooden      Maroon  25000
1  Dining Table          Plywood      Yellow  20000
2         Chair          Plastic         Red   1500
3          Sofa  Stainless steel      Silver  55000
4         Chair           Wooden  Light Blue   2500
5  Dining Table         Aluminum      Golden  65000

In [39]:
# Creating A dataset 

col = ['Name','Age','ML','Python']

data = [
    ['Rishi',20,76,80],
    ['Aditya',22,89,78],
    ['Sahil',21,78,89],
    ['Nishant',23,78,67],
    ['Sanjil',22,88,87]
]

df = pd.DataFrame(data,columns=col)
df

Name  Age  ML  Python
0    Rishi   20  76      80
1   Aditya   22  89      78
2    Sahil   21  78      89
3  Nishant   23  78      67
4   Sanjil   22  88      87

In [40]:
df = pd.DataFrame(data=data,columns=col)
df

Name  Age  ML  Python
0    Rishi   20  76      80
1   Aditya   22  89      78
2    Sahil   21  78      89
3  Nishant   23  78      67
4   Sanjil   22  88      87

In [41]:
# providing Index
df = pd.DataFrame(data = data,index=['Rank1',
                                     'Rank2',
                                     'Rank3',
                                     'Rank4',
                                     'Rank5'],columns = col)
df


Name  Age  ML  Python
Rank1    Rishi   20  76      80
Rank2   Aditya   22  89      78
Rank3    Sahil   21  78      89
Rank4  Nishant   23  78      67
Rank5   Sanjil   22  88      87

In [42]:
# Crreating Dataframe with Python Dictionary 

name = ["javed","ramachal","rajat","swapnil","rohit","prabhat","shweta","Sid","yuvi","siddu"]
age = [22,23,24,25,23,21,19,23,24,25]
ml = [67,78,67,78,89,90,87,67,45,89]
python =[89,78,65,67,78,67,56,57,89,78]

dic = {
    'Name':name,
    'Age':age,
    'ML':ml,
    'Python':python
}

df = pd.DataFrame(data = dic)
df

Name  Age  ML  Python
0     javed   22  67      89
1  ramachal   23  78      78
2     rajat   24  67      65
3   swapnil   25  78      67
4     rohit   23  89      78
5   prabhat   21  90      67
6    shweta   19  87      56
7       Sid   23  67      57
8      yuvi   24  45      89
9     siddu   25  89      78

In [43]:
df = pd.DataFrame(data = dic,index=np.arange(1,11))
df

Name  Age  ML  Python
1      javed   22  67      89
2   ramachal   23  78      78
3      rajat   24  67      65
4    swapnil   25  78      67
5      rohit   23  89      78
6    prabhat   21  90      67
7     shweta   19  87      56
8        Sid   23  67      57
9       yuvi   24  45      89
10     siddu   25  89      78

In [45]:
arr = np.arange(1,5).reshape(4,1,1)
arr

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [46]:
arr = np.arange(1,5).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [48]:
# Creating DataFrame with Numpy array
df = pd.DataFrame(data=np.arange(1,5).reshape(2,2))
df
# bydefault it has taken 0,1 as index and column name also

0  1
0  1  2
1  3  4

In [49]:
# lets assign column name to the above program
arr = np.arange(1,5).reshape(2,2)
df = pd.DataFrame(data = arr,index=[1,2],columns=['col1','col2'])
df

col1  col2
1     1     2
2     3     4

In [50]:
# Creating dataframe with Series

d = {
    'one':pd.Series([1,2,3],index=['a','b','c']),
    'two':pd.Series(data=[1,2,3,4],index=['a','b','c','d'])
}

df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

    Whenever there is "Nan" value in any column then the datatype of that column will get convert from 'int' to 'float'

In [51]:
d = {
    "one":pd.Series([1,2,3],index=["a","b","c"]),
    "two":pd.Series([1,2,3,4],index=["A","b","c","d"])
}

df = pd.DataFrame(d)
df

one  two
A  NaN  1.0
a  1.0  NaN
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

    If you notice something on both the column there is Nan  values so both the column has datatype as "float"

In [52]:
np.random.randn(3,3,3)

array([[[-0.53710255, -0.34259817, -1.06488053],
        [ 0.13126346, -0.16551225,  0.09016919],
        [-0.65661822,  1.58757585,  0.03350624]],

       [[ 0.99129208,  1.22956172,  1.06525527],
        [ 1.29683629,  0.98337039, -1.1650752 ],
        [ 0.82554118, -0.80385888,  0.35250846]],

       [[-0.61228142, -1.99066795, -1.5223512 ],
        [-1.14026309, -0.72256977, -1.6316895 ],
        [-1.06635182,  0.48233219,  1.06512854]]])

In [57]:
# Creatinf df With Random 
# np.random.randn(10,4) = 10 Rows and 4 Columns 
df  =pd.DataFrame(np.random.rand(10,4),columns=['A','B','C','D'])
df

A         B         C         D
0  0.929149  0.789257  0.567232  0.529431
1  0.217952  0.202075  0.111298  0.208791
2  0.642277  0.798193  0.830823  0.242196
3  0.614469  0.065140  0.630600  0.945291
4  0.055189  0.699400  0.761668  0.697132
5  0.235924  0.581687  0.906788  0.072224
6  0.170104  0.417991  0.191727  0.075916
7  0.403253  0.411775  0.567698  0.504358
8  0.205195  0.829844  0.880084  0.347032
9  0.872810  0.841938  0.874238  0.014949

In [58]:
# to make the value fix and which will not change when we try to run
np.random.seed(111)
df = pd.DataFrame(np.random.rand(10,4),index=np.arange(1,11),columns=["A","B",
                                                                     "C","D"])
df

A         B         C         D
1   0.612170  0.169070  0.436059  0.769262
2   0.295325  0.149163  0.022478  0.420224
3   0.238682  0.337656  0.990712  0.237726
4   0.081193  0.669600  0.621243  0.274254
5   0.466221  0.118368  0.073958  0.900774
6   0.793963  0.840570  0.815207  0.990955
7   0.577274  0.813767  0.421318  0.027448
8   0.454137  0.105326  0.817220  0.697728
9   0.565285  0.274227  0.998474  0.138042
10  0.615416  0.485036  0.405027  0.727849

## Panel 

In [59]:
data = np.random.rand(2,4,5)
data
# 2 matrices
# 4 rows in each matrices
# 5 columns or 5 values in each rows

array([[[0.32281393, 0.40054555, 0.3189664 , 0.94722183, 0.91870836],
        [0.81384438, 0.03407709, 0.94337287, 0.95043916, 0.80659105],
        [0.48127804, 0.96675923, 0.41697908, 0.31884013, 0.01644282],
        [0.03818193, 0.05308965, 0.12796081, 0.03338316, 0.22642109]],

       [[0.54390891, 0.17862581, 0.17934478, 0.14961322, 0.68301313],
        [0.46900855, 0.76824793, 0.66881406, 0.44126818, 0.59522545],
        [0.46165662, 0.96326687, 0.14781138, 0.90681313, 0.49792484],
        [0.59249847, 0.68465799, 0.17745066, 0.86468549, 0.48208878]]])

In [66]:
data  = np.random.rand(5,5,5)
df = pd.Panel(data)
df

AttributeError: module 'pandas' has no attribute 'Panel'

In [67]:
data  = np.random.rand(5,5)
df = pd.Panel(data)
df

AttributeError: module 'pandas' has no attribute 'Panel'

In [68]:
data  = np.random.rand(5,5,5)
df = pd.panel(data)
df

AttributeError: module 'pandas' has no attribute 'panel'

In [69]:
data  = np.random.rand(5,5)
df = pd.panel(data)
df

AttributeError: module 'pandas' has no attribute 'panel'

In [60]:
np.random.rand(5,5,5)

array([[[0.06934179, 0.36473134, 0.36150419, 0.4720635 , 0.17948485],
        [0.17527984, 0.9491296 , 0.65568231, 0.13499553, 0.92778583],
        [0.84179162, 0.05277604, 0.20368352, 0.87250164, 0.67384806],
        [0.29727251, 0.73441308, 0.61834027, 0.21049925, 0.80206458],
        [0.05910708, 0.3082233 , 0.20736749, 0.97219083, 0.90941858]],

       [[0.67645419, 0.1151861 , 0.95798068, 0.09171332, 0.62979647],
        [0.90290054, 0.33979728, 0.65280429, 0.92515852, 0.3739835 ],
        [0.77136418, 0.89616473, 0.62017809, 0.15106007, 0.37491975],
        [0.63584055, 0.45907073, 0.53223817, 0.35229218, 0.65986196],
        [0.47652343, 0.45459494, 0.12479753, 0.41247224, 0.27309572]],

       [[0.34674088, 0.97437429, 0.21558059, 0.68284291, 0.03180999],
        [0.83538294, 0.70165234, 0.96594378, 0.59181621, 0.21734542],
        [0.71922624, 0.03086999, 0.41870795, 0.28122512, 0.10624436],
        [0.42634622, 0.84057751, 0.11041134, 0.98665245, 0.23329332],
        [0.72141

In [61]:
np.random.rand(5,5,5).size

125

In [62]:
np.random.rand(5,5,5).shape

(5, 5, 5)

In [63]:
np.random.rand(5,5,5).T

array([[[0.21279501, 0.64562184, 0.47664889, 0.29132076, 0.77854437],
        [0.30064677, 0.66042708, 0.3055096 , 0.75622125, 0.96118923],
        [0.7443455 , 0.04386589, 0.26477642, 0.44172762, 0.4176384 ],
        [0.72475182, 0.52651545, 0.56525928, 0.8057051 , 0.73471879],
        [0.51118002, 0.21973297, 0.43206261, 0.40085107, 0.84005771]],

       [[0.1273003 , 0.76275001, 0.48407768, 0.53971038, 0.5443829 ],
        [0.6397423 , 0.99946302, 0.85357087, 0.75293596, 0.97287258],
        [0.38758044, 0.31150273, 0.48399662, 0.61877927, 0.18772011],
        [0.03343351, 0.06789435, 0.37009804, 0.59923087, 0.97139815],
        [0.01000576, 0.34140194, 0.7902691 , 0.81494678, 0.04762983]],

       [[0.24843898, 0.24844986, 0.49087614, 0.45293211, 0.41238821],
        [0.54173595, 0.03268261, 0.74633972, 0.72154437, 0.23168039],
        [0.67615592, 0.14799995, 0.54891461, 0.60810942, 0.64972823],
        [0.44989604, 0.34147738, 0.63545084, 0.21827101, 0.92209176],
        [0.85113

In [64]:
np.random.rand(5,5,5).dtype

dtype('float64')

In [65]:
np.random.rand(5,5,5).ndim

3