## Slicing in Numpy - Chapter 3 Practice 1

In [1]:
import numpy as np 

## 1D Array

In [2]:
a = np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [3]:
a[::]

array([10, 20, 30, 40, 50, 60])

In [4]:
a[0:6:1]

array([10, 20, 30, 40, 50, 60])

In [5]:
a[0:]

array([10, 20, 30, 40, 50, 60])

In [6]:
a[::-1]

array([60, 50, 40, 30, 20, 10])

In [7]:
a[0:6:2]

array([10, 30, 50])

In [8]:
a[1::2]

array([20, 40, 60])

In [9]:
a[1:6:2]

array([20, 40, 60])

In [10]:
a[:4]

array([10, 20, 30, 40])

In [11]:
a[2:]

array([30, 40, 50, 60])

In [12]:
a[::2]

array([10, 30, 50])

In [13]:
a[-1::1]

array([60])

In [14]:
a[-1::-1]

array([60, 50, 40, 30, 20, 10])

In [15]:
a[::-1]

array([60, 50, 40, 30, 20, 10])

In [17]:
a[::3]

array([10, 40])

In [18]:
a[::4]

array([10, 50])

In [19]:
a[::5]

array([10, 60])

In [20]:
a[::6]

array([10])

## 2D

In [21]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
b[1,1]

50

In [23]:
# if you see the abouve output it just giving the output 
# but not in the form of an array 
# if i try the same abpve output in array form
b[1:2,1:2]
# here i did the slicing and due to that we got the output in, 
# array form


array([[50]])

In [27]:
b[:,1:]

array([[20, 30],
       [50, 60]])

In [28]:
b[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [29]:
b[0:2,0:3]

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
b= np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [31]:
b[2,1]

80

In [32]:
b[2,1:2]

array([80])

In [37]:
b[2:3,1:2]

array([[80]])

In [38]:
b[0,1:2]

array([20])

### Arithmatic Operator

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
np.shape(a)

(3, 3)

In [44]:
np.shape(a)

(3, 3)

In [45]:
np.shares_memory(a,b)

False

In [48]:
a.shape

(3, 3)

In [49]:
b.shape

(3, 3)

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
# Addition 
np.add(a,b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
np.add(b,a)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [54]:
c = np.array([10,20,30])
c

array([10, 20, 30])

In [55]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
np.add(a,c)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [60]:
np.add(c,a)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [59]:
np.add(b,c)

array([[11, 21, 31],
       [11, 21, 31],
       [11, 21, 31]])

In [61]:
np.add(c,b)

array([[11, 21, 31],
       [11, 21, 31],
       [11, 21, 31]])

In [63]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
c

array([10, 20, 30])

In [62]:
np.subtract(a,c)

array([[ -9, -18, -27],
       [ -6, -15, -24],
       [ -3, -12, -21]])

In [65]:
np.divide(a,b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [66]:
np.mod(c,a)

array([[0, 0, 0],
       [2, 0, 0],
       [3, 4, 3]])

### View  And Copy - Chapter 4
  - when we slice a subarray from an array it may be done by two Array 
   - 1. it is making view
   - 2. Using a copy of it
  - But there is some difference between both of them.
  - if you make a view of an array any changes made to the array will be replicated to Original Array,
  - whereas if you make a copy of it, and make any changes to copied subarray will bot reflect on the Original Array.
  
  - Bydefault an Array is set on View.
  
## View 

In [67]:
import numpy as np

In [68]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
slic = a[3:6]

In [70]:
slic

array([40, 50, 60])

In [72]:
# lets try to change the value of variable 'slicing'
slic[:] = 0
slic

array([0, 0, 0])

In [73]:
# let try to print the Original Array 
# to see that if it has effected our original array or not
a
# and it has did the changes oin the Original Array

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

## Copy

In [79]:
b = np.array([10,20,30,40,50,60,70,80,90])
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
slic = b[3:6].copy()

In [81]:
slic

array([40, 50, 60])

In [82]:
slic[:]=0

In [83]:
slic

array([0, 0, 0])

In [84]:
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
b[:1:]

array([[10, 20, 30]])

In [26]:
b[:2:]

array([[10, 20, 30],
       [40, 50, 60]])

### Numpy Array Selection
#### This is called process Masking.

In [85]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
mask = a>4
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
a[mask]

array([ 5,  6,  7,  8,  9, 10])

In [89]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [90]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [91]:
a[a>=4]

array([ 4,  5,  6,  7,  8,  9, 10])

In [92]:
a[a>=4].shape

(7,)

In [93]:
a[a>=4].reshape(1,7)

array([[ 4,  5,  6,  7,  8,  9, 10]])

In [94]:
name = np.array(["rishi","rohit","aditya","sanjil","nishant"])
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant'], dtype='<U7')

In [95]:
x = 'rishi'
name == x

array([ True, False, False, False, False])

In [96]:
name[name==x]

array(['rishi'], dtype='<U7')

In [97]:
name!=x

array([False,  True,  True,  True,  True])

In [98]:
name[name!=x]

array(['rohit', 'aditya', 'sanjil', 'nishant'], dtype='<U7')

In [99]:
name = np.array(["rishi","rohit","aditya","sanjil","nishant","rishi","rishi","sanjil"])
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant', 'rishi', 'rishi',
       'sanjil'], dtype='<U7')

In [100]:
(name=='rishi') | (name=='sanjil')

array([ True, False, False,  True, False,  True,  True,  True])

In [101]:
name[(name=='rishi') | (name=='sanjil')]

array(['rishi', 'sanjil', 'rishi', 'rishi', 'sanjil'], dtype='<U7')

In [102]:
# select all the values which is not rishi and 
# assign those value as 'Javed'
name

array(['rishi', 'rohit', 'aditya', 'sanjil', 'nishant', 'rishi', 'rishi',
       'sanjil'], dtype='<U7')

In [103]:
name[name!='rishi']='javed'

In [104]:
name

array(['rishi', 'javed', 'javed', 'javed', 'javed', 'rishi', 'rishi',
       'javed'], dtype='<U7')

In [105]:
a = np.array([27,4,1,5,7,39])
a

array([27,  4,  1,  5,  7, 39])

In [106]:
np.min(a)

1

In [107]:
a.min()

1

In [108]:
a.max()

39

In [110]:
np.max(a)

39

In [111]:
np.argmin(a)

2

In [113]:
a.argmin()

2

In [114]:
a.argmax()

5

In [115]:
np.sqrt(a)

np.sin(a)

np.cos(a)

np.quantile(a,0.25)
# Quantile 1 - 25%

np.quantile(a,0.75)
# Quantile 3 - 75%

np.quantile(a,0.50)
# Quantile 2 - 50% Median 

6.0

In [116]:
np.sqrt(a)

array([5.19615242, 2.        , 1.        , 2.23606798, 2.64575131,
       6.244998  ])

In [117]:
np.sin(a)

array([ 0.95637593, -0.7568025 ,  0.84147098, -0.95892427,  0.6569866 ,
        0.96379539])

In [118]:
np.cos(a)

array([-0.29213881, -0.65364362,  0.54030231,  0.28366219,  0.75390225,
        0.26664293])

In [119]:
np.quantile(a,0.25)
# Quantile 1 - 25%

4.25

In [120]:
np.quantile(a,0.75)
# Quantile 3 - 75%

22.0

In [121]:
np.quantile(a,0.50)
# Quantile 2 - 50% Median

6.0