## Day 1 - Numpy Chapter 1

### What is Numpy?
 - Introduction to Numpy:-
  - Numpy is a Python Package and it stands for Numerical Python.
  - This was created in 2005 and it was developed by Travis Oliphant.
  - It Provides lot of Functions to work in a domain of Linear Algebra and Matrix.
  - It provides function related to to Arrays.
  - It creates an Array called ndarray.
  - Most of thge part of numpy created in C and C++.

### Operations in Numpy 
  - Mathematical and Statistical and Logical Operations on Array.
  - It is used for Scientific Calculation.
  - Operations are related to mathematics, Statistics, Linear Algebra and Random Number Generations.
  - Transformation and routine for shape manipulation of the Array.

In [64]:
%%timeit

a = []

for i in range(1,15):
    a.append(i**2)

3.27 µs ± 48.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [65]:
%timeit [i**2 for i in range(1,15)]

2.93 µs ± 22.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Numpy 

In [66]:
# importing the Numpy Library 

import numpy as np 

In [67]:
x=[1,2,3]
x

[1, 2, 3]

In [68]:
type(x)

list

In [69]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [70]:
type(x)

numpy.ndarray

#### 1D Array

In [71]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [72]:
a = [1,2,3,4]

arr = np.array(a)
arr

array([1, 2, 3, 4])

In [73]:
# take user Input 
a = []
no = eval(input("enter total no. of Observation: "))
cnt = 1
for i in range(no):
    val = int(input(f"enter value{cnt}: "))
    a.append(val)
    cnt+=1
a = np.array(a)
a

enter total no. of Observation: 3
enter value1: 1
enter value2: 2
enter value3: 3


array([1, 2, 3])

#### 2D Array 

In [74]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# checking the type
type(a)

numpy.ndarray

In [76]:
# To check the Dimensions 
print(np.ndim(a))
print(a.ndim)

2
2


In [77]:
# checking the dtype (datatype)
print(a.dtype)

int32


#### 3D Array

In [78]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
# checking  the dimensions
a.ndim

3

### Attribute of Numpy 

In [80]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
# gives shape of an matrix or array in the row and columnwise.
a.shape
# it says 2 rows and 3 columns 

(2, 3)

In [82]:
# Return the total no. of observation in an array.
a.size

6

In [141]:
# This will change the shape of an Array Temporary
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# alternate way to reshape
a.shape=(3,2)

In [86]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
a.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [90]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
# Transpose
# this will convert rpws into column amd columns into rows 
a.T
# changes the shape of an array/ matrix


array([[1, 3, 5],
       [2, 4, 6]])

In [92]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
# It will return you the dimensions of an Array.
a.ndim

2

#### Joining of Array

In [94]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [95]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
np.arange(1,7).T

array([1, 2, 3, 4, 5, 6])

In [97]:
np.arange(1,7).reshape(2,3).shape

(2, 3)

In [98]:
np.arange(1,7).reshape(2,3).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
np.arange(1,7).reshape(2,3).T.shape

(3, 2)

In [100]:
a = np.arange(1,7).reshape(2,3)

b = np.arange(7,13).reshape(2,3)

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

#### Concatenate

In [144]:
#a.Concatenate((arr1,arr2))
# It is used to join two different Array and it takes tuples.

In [145]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [146]:
np.concatenate((b,a))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [106]:
np.concatenate((a,b)).T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

#### hstack and vstack

In [147]:
# hstack 
# it is used to concatenate two differents Arrays horizontally 
# (column wise)
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [148]:
# vstack
# It is used to concatenate two different Array vertically 
# (row wise)
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.hstack((b,a))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [110]:
np.vstack((b,a))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [149]:
# stack
# it is usewd to convert 2D Array into 3D Array
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
np.stack((b,a))

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [151]:
# ravel 
# It is used to convert 2D into 1D Array
# Return a contiguous flattened array.
# np.ravel(a)
print(a)
np.ravel(a)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

#### Append

In [114]:
# append(arr,list of element)
# It is used to add the element in the existing Array.

c = np.arange(1,7)
c

array([1, 2, 3, 4, 5, 6])

In [115]:
np.append(c,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.append(a,[[7,8,9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.append(a,[[7,8,9]],axis=0) 
# axis = 0 means row-wise horizopntally

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
np.append(a,[[7,8,9]],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [122]:
np.append(a,[7,8,9],axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

#### Insert 

In [ ]:
# insert 
# it is used to add the element at specific index.

In [125]:
d = np.arange(2,6)
d

array([2, 3, 4, 5])

In [127]:
np.insert(d,0,2)

array([2, 2, 3, 4, 5])

In [128]:
d

array([2, 3, 4, 5])

In [129]:
d = np.insert(d,0,12)

In [130]:
d

array([12,  2,  3,  4,  5])

#### Delete

In [131]:
# delete(array, list of element index)
# It is used to delete element the from the array.

In [132]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [133]:
np.delete(x,[0,1])

array([3, 4, 5])

In [137]:
np.delete(x,[0:])

SyntaxError: invalid syntax (921011564.py, line 1)

In [139]:
np.delete(x,0)

array([2, 3, 4, 5])

### Day 2 - Numpy Array Creation Routine. Chapter 2

In [1]:
import numpy as np 

In [2]:
# empty(shape,dtype)
# It creates an uninitialize Array of Specified Shape and Datatype
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [156]:
a = np.empty([2,2])
a

array([[1.10385477e-311, 1.10343781e-311],
       [4.15015143e-321, 3.79442416e-321]])

In [157]:
print(a.dtype)

float64


In [158]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [159]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 9.98012605e-321],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [160]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [162]:
np.empty([2, 2])        #uninitialized

array([[9.98012605e-321, 1.78019082e-306],
       [1.37959740e-306, 2.29178686e-312]])

In [163]:
np.empty([3,2],dtype='str')

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [173]:
# Zeros(shape, dtype)
# it Returns new array of Specialized size and type filled with ones
np.zeros([3,2])
# bydefault dtype is float

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [172]:
np.zeros([2,2],dtype='str')

array([['', ''],
       ['', '']], dtype='<U1')

In [171]:
np.zeros([2,3],dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [170]:
np.zeros([2,3],dtype='int')*5

array([[0, 0, 0],
       [0, 0, 0]])

In [174]:
# ones
# it returns new array of specified size and type filled with ones 
# np.ones([shape],dtype=)
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [175]:
np.ones([5,4],dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [176]:
np.ones([4,4],dtype='int')*5

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [177]:
np.ones([4,4],dtype='int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [178]:
np.ones([5,5],dtype='str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [181]:
# eye()
# it is identity matrix 
# it takes square matrix ---> np.eye(3) means 3x3 matrix
# Initialize "ones" on all diagonal position.
# initialize "zeros" on non-diagonal position.
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [182]:
np.eye(1)

array([[1.]])

In [183]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [184]:
np.eye(3,dtype='float')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [185]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [186]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [187]:
np.eye(4,3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [1]:
import numpy as np 

In [14]:
# full()
# this function will initailize the elemet in the given values 
# np.full(shape,values)
a = np.full([2,2],100)
a

array([[100, 100],
       [100, 100]])

In [9]:
print(a.dtype)

int32


In [3]:
np.full(12,100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [5]:
np.full([3,4],12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [15]:
b=np.full([4,5],12,dtype='float')
b

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

In [11]:
print(b.dtype)

float64


In [13]:
c= np.full([3,3],12.)
c

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]])

In [16]:
print(c.dtype)

float64


diag()
 - This function creates a two-dimensional array with all the diagonal elements as the given and rest as 'zeros'

In [17]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [19]:
a = np.diag([1,2,4,8])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])

In [21]:
np.diag(a)
# it will return the diagnoanl value which in an array exists

array([1, 2, 4, 8])

In [25]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.diag([1,2,3,4]).reshape(4,4)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag([1,2,3,4]).reshape(16,)

array([1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4])

In [26]:
np.diag([1,2,3,4]).reshape(1,16)

array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4]])

In [28]:
# randint()
# tihis functionns is used to generate a random number between a goven range
# np.random.randint(min,max,total values)
np.random.randint(1,10,10)

array([9, 3, 9, 3, 1, 6, 4, 8, 9, 3])

In [29]:
np.random.randint(21,10,10)

ValueError: low >= high

In [31]:
np.random.randint(-10,10,10)

array([ 9, -7, -1,  5, -2,  3, -2, -5,  9,  1])

In [30]:
np.random.randint(-20,10,10)

array([  8,  -4, -13,   9,  -3,  -7, -11, -19,   4,   8])

In [32]:
# rand()
# this function is used to generate a random value,
# between 0 to 1
np.random.rand(2,3)

array([[0.38341588, 0.26985621, 0.04376424],
       [0.30659486, 0.45288516, 0.04455403]])

In [33]:
np.random.rand(3,2).T

array([[0.0444551 , 0.21094104, 0.24355664],
       [0.84226947, 0.49110627, 0.07094424]])

In [37]:
a=np.random.rand(4,4)
a

array([[0.01096477, 0.39082179, 0.14101994, 0.54441178],
       [0.32574869, 0.4037601 , 0.55288688, 0.72941114],
       [0.44589875, 0.326176  , 0.1768774 , 0.76902004],
       [0.53751935, 0.8992252 , 0.71326352, 0.22484159]])

In [39]:
print(type(a))
print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
float64
2


In [40]:
# randn
# it will genrate a random value closed to 'zero'
# it will return a positive or negative value close to 'zero'
np.random.randn(5)

array([ 0.62558263,  0.0842205 ,  0.21652578,  0.18653089, -0.43527045])

In [41]:
np.random.randn(2,3)

array([[-0.36897158,  2.26709946, -0.6917135 ],
       [-1.88271982,  0.82744379,  0.94055363]])

In [43]:
np.random.randn(4,4)

array([[ 0.41493371, -0.06837008,  0.37727498, -1.91119798],
       [ 0.38187786, -1.40022961,  0.16410527,  0.65500227],
       [-0.05387034,  0.5295228 ,  0.17938679, -0.25787923],
       [-1.40489059, -1.23584558,  0.32740077, -0.01640456]])

In [44]:
np.random.randn(12,)

array([-0.24800594, -1.95831357, -1.01850377,  1.51742775,  0.17655028,
       -0.64772207, -0.05203179, -0.58441296,  0.38337318, -0.34271842,
       -1.59342543, -0.63204343])

In [45]:
np.random.randn(1,12)

array([[-1.9262265 , -0.63095131, -0.89911767, -0.37010511,  0.46010282,
         0.61793867,  0.0762069 ,  1.18729579,  0.54231039, -0.99042368,
        -0.34705399, -2.33629416]])

#### seed() functions
 - we know that randint() generates random number a new set of number everytime we run the program a new set of random numbers is generated but what if we want to fix this generation of number in this case we use 'seed' function 

In [46]:
np.random.seed(0)
a = np.random.randint(1,100,10)
a

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [47]:
set0 = np.random.seed(0)
a = np.random.randint(1,100,10)
a

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [48]:
np.random.seed(0)
np.random.randint(1,100,11)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71])

In [51]:
np.random.seed(1)
np.random.randint(1,3,10)

array([2, 2, 1, 1, 2, 2, 2, 2, 2, 1])

### Reshape of an Array 

In [52]:
a = np.random.randint(1,100,12)

In [53]:
a

array([17,  2, 77, 72,  7, 26, 51, 21, 19, 85, 12, 29])

In [54]:
a.reshape(4,3)

array([[17,  2, 77],
       [72,  7, 26],
       [51, 21, 19],
       [85, 12, 29]])

In [55]:
a.reshape(3,4)

array([[17,  2, 77, 72],
       [ 7, 26, 51, 21],
       [19, 85, 12, 29]])

In [56]:
a.reshape(12,)
# series - one dimensional 

array([17,  2, 77, 72,  7, 26, 51, 21, 19, 85, 12, 29])

In [58]:
a.reshape(1,12)
# two - dimensional 

array([[17,  2, 77, 72,  7, 26, 51, 21, 19, 85, 12, 29]])

### Function in Numpy 

In [60]:
# arange()
# it is an array of evenly spaced numbers just like a python's list
# array with numerical python 
# np.arange(start,stop, step, dtype)
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [61]:
np.arange(1,20,2,dtype='float')

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [62]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [63]:
np.arange(20,10,-1).reshape(2,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [65]:
np.arange(20,10,-1).reshape(2,5).T

array([[20, 15],
       [19, 14],
       [18, 13],
       [17, 12],
       [16, 11]])

In [67]:
# linspace()
# np.linspace(start,stop,num,endpoint,retstep)
a=np.linspace(10,20)
a
# bydefault it will print 50 no. of obseravtions 

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [68]:
a.size
# # bydefault it will print 50 no. of obseravtions 
# to change it will use "num"

50

In [72]:
np.linspace(10,20,num=20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [73]:
np.linspace(10,20,num=20).size

20

In [75]:
np.linspace(10,20,num=20,endpoint=False)
# endpoint will not consider the last element which was 20 in this case

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [76]:
np.linspace(10,20,num=10,endpoint=False,retstep=True)
# restep will let you know what is the increment size betn the obseravtions

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), 1.0)

In [80]:
# logspace 
# logspace doesn't have retstep
np.logspace(10,20,num=20)
# it will give us logarithm values 
# base bydefault is 10
# # bydefault it will print 50 no. of obseravtions 

array([1.00000000e+10, 3.35981829e+10, 1.12883789e+11, 3.79269019e+11,
       1.27427499e+12, 4.28133240e+12, 1.43844989e+13, 4.83293024e+13,
       1.62377674e+14, 5.45559478e+14, 1.83298071e+15, 6.15848211e+15,
       2.06913808e+16, 6.95192796e+16, 2.33572147e+17, 7.84759970e+17,
       2.63665090e+18, 8.85866790e+18, 2.97635144e+19, 1.00000000e+20])

In [81]:
# lets change the base 
np.logspace(10,20,num=20,base=3)

array([5.90490000e+04, 1.05275908e+05, 1.87691864e+05, 3.34627706e+05,
       5.96593265e+05, 1.06364033e+06, 1.89631834e+06, 3.38086396e+06,
       6.02759614e+06, 1.07463405e+07, 1.91591857e+07, 3.41580835e+07,
       6.08989697e+07, 1.08574139e+08, 1.93572137e+08, 3.45111392e+08,
       6.15284174e+08, 1.09696354e+09, 1.95572886e+09, 3.48678440e+09])

In [84]:
# lets try to save an array 
a=np.arange(1,7).reshape(2,3)

In [85]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
# lets save this array 
np.savetxt('array.txt',a)

In [90]:
# let read the array file which we saved in a txt format 
y = np.loadtxt('array.txt')
y
# the dtype is 'float' 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [91]:
# lets change the dtype
y = np.loadtxt('array.txt',dtype='int')
y

C:\Users\HRISHIKESH\AppData\Local\Temp\ipykernel_2904\2952651259.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  y = np.loadtxt('array.txt',dtype='int')


array([[1, 2, 3],
       [4, 5, 6]])